version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    networks:
      my_network:
        ipv4_address: 172.20.0.2
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  python_script:
    build:
      context: ./api
      dockerfile: dockerfile
    container_name: python_script
    depends_on:
      - mongodb
    # volumes:
    #   - ./api/app.py:/app/app.py 
    #   - ./api/routes.py:/app/routes.py
    networks:
      my_network:
        ipv4_address: 172.20.0.3
    environment:
      - MONGO_URI=mongodb://mongodb:27017/DB
    ports:
      - "8080:8080"
    command: bash -c "while true; do python app.py; sleep 180; done"

  dashboard:
    build:
      context: ./dashboard
      dockerfile: dockerfile
    container_name: dashboard
    depends_on:
      - mongodb
      - python_script
    # volumes:
    #   - ./dashboard/dashboard.py:/app/dashboard.py 
    networks:
      my_network:
        ipv4_address: 172.20.0.4
    ports:
      - "8500:8500"
    command: streamlit run dashboard.py --server.port 8500

volumes:
  mongodb_data:


networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16