# Utilise une image de base avec Python
FROM python:3.9

# Copie les fichiers de l'API dans le conteneur
COPY . /app

# Définit le répertoire de travail
WORKDIR /app

# Installe les dépendances de compilation C nécessaires
RUN apt-get update && apt-get install -y gcc

# Installe les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Expose le port 8080
EXPOSE 8182

# Commande à exécuter lors du démarrage du conteneur
CMD ["python", "app.py"]
